import { getQuestionReviewMode } from "../utils/question-metadata.js";
import type { QuestionBankEntry } from "./question-bank.types.js";

export const QUESTION_BANK_SAMPLE_ENTRIES: QuestionBankEntry[] = [
  {
    id: "Q-204",
    stem: "What is the worst-case time complexity of quicksort when the pivot repeatedly splits the array unevenly?",
    type: "SINGLE_CHOICE",
    difficulty: "HARD",
    topicId: "algorithms",
    topicName: "Algorithms",
    reviewMode: getQuestionReviewMode("SINGLE_CHOICE"),
    usageCount: 3,
    updatedAt: "2026-04-09T10:30:00.000Z",
    answerPreview: ["O(n^2)"],
    explanation:
      "The worst case occurs when partitioning is highly unbalanced, producing quadratic work across recursive calls.",
  },
  {
    id: "Q-219",
    stem: "Which traversal of a binary search tree lists the keys in sorted order?",
    type: "SINGLE_CHOICE",
    difficulty: "EASY",
    topicId: "data-structures",
    topicName: "Data Structures",
    reviewMode: getQuestionReviewMode("SINGLE_CHOICE"),
    usageCount: 5,
    updatedAt: "2026-04-11T08:05:00.000Z",
    answerPreview: ["In-order traversal"],
    explanation:
      "In-order traversal visits left subtree, node, and right subtree, which yields ascending keys in a BST.",
  },
  {
    id: "Q-225",
    stem: "Which property is always true for a binary search tree node relative to its left and right subtrees?",
    type: "SINGLE_CHOICE",
    difficulty: "MEDIUM",
    topicId: "data-structures",
    topicName: "Data Structures",
    reviewMode: getQuestionReviewMode("SINGLE_CHOICE"),
    usageCount: 2,
    updatedAt: "2026-04-08T14:20:00.000Z",
    answerPreview: ["All left subtree keys are smaller and all right subtree keys are larger"],
    explanation:
      "The BST ordering invariant compares every key in each subtree against the current node, not only the immediate children.",
  },
  {
    id: "Q-238",
    stem: "Explain the role of virtual memory and describe two benefits it gives to a multitasking operating system.",
    type: "SHORT_TEXT",
    difficulty: "MEDIUM",
    topicId: "operating-systems",
    topicName: "Operating Systems",
    reviewMode: getQuestionReviewMode("SHORT_TEXT"),
    usageCount: 4,
    updatedAt: "2026-04-10T06:45:00.000Z",
    answerPreview: [
      "Virtual memory creates an abstraction of large contiguous memory and enables isolation plus efficient memory utilization.",
    ],
    explanation:
      "A strong response should mention logical-to-physical mapping and benefits such as process isolation, demand paging, or larger address spaces.",
  },
  {
    id: "Q-241",
    stem: "True or false: A system cannot enter deadlock if at least one of the Coffman conditions is permanently prevented.",
    type: "TRUE_FALSE",
    difficulty: "HARD",
    topicId: "operating-systems",
    topicName: "Operating Systems",
    reviewMode: getQuestionReviewMode("TRUE_FALSE"),
    usageCount: 2,
    updatedAt: "2026-04-07T12:15:00.000Z",
    answerPreview: ["True"],
    explanation:
      "Deadlock requires all Coffman conditions to hold simultaneously, so violating any one of them prevents deadlock.",
  },
  {
    id: "Q-248",
    stem: "Which steps are part of the TCP three-way handshake used to establish a reliable connection?",
    type: "MULTIPLE_CHOICE",
    difficulty: "EASY",
    topicId: "networks",
    topicName: "Networks",
    reviewMode: getQuestionReviewMode("MULTIPLE_CHOICE"),
    usageCount: 3,
    updatedAt: "2026-04-10T17:40:00.000Z",
    answerPreview: ["Client sends SYN", "Server replies with SYN-ACK", "Client sends ACK"],
    explanation:
      "The exchange synchronizes sequence numbers and confirms both endpoints are ready to transmit.",
  },
  {
    id: "Q-252",
    stem: "Which network protocol guarantees ordered and reliable byte-stream delivery between hosts?",
    type: "SINGLE_CHOICE",
    difficulty: "EASY",
    topicId: "networks",
    topicName: "Networks",
    reviewMode: getQuestionReviewMode("SINGLE_CHOICE"),
    usageCount: 6,
    updatedAt: "2026-04-06T09:50:00.000Z",
    answerPreview: ["TCP"],
    explanation:
      "TCP adds sequencing, acknowledgements, and retransmission to deliver a reliable ordered stream.",
  },
  {
    id: "Q-261",
    stem: "Which normal form removes transitive dependencies from a relation after it already satisfies second normal form?",
    type: "SINGLE_CHOICE",
    difficulty: "MEDIUM",
    topicId: "database-systems",
    topicName: "Database Systems",
    reviewMode: getQuestionReviewMode("SINGLE_CHOICE"),
    usageCount: 4,
    updatedAt: "2026-04-09T05:25:00.000Z",
    answerPreview: ["Third Normal Form"],
    explanation:
      "Third normal form targets non-key attributes that depend transitively on a candidate key.",
  },
  {
    id: "Q-266",
    stem: "Discuss the differences between breadth-first search and depth-first search, including one scenario where each is preferred.",
    type: "LONG_TEXT",
    difficulty: "HARD",
    topicId: "algorithms",
    topicName: "Algorithms",
    reviewMode: getQuestionReviewMode("LONG_TEXT"),
    usageCount: 1,
    updatedAt: "2026-04-12T07:15:00.000Z",
    answerPreview: [
      "Breadth-first search explores level by level and is preferred for shortest paths in unweighted graphs, while depth-first search is preferred for exhaustive traversal and backtracking.",
    ],
    explanation:
      "A high-quality answer should compare traversal order, data structures, complexity, and practical use cases.",
  },
  {
    id: "Q-274",
    stem: "Select the constraints that are part of RESTful architectural style for web services.",
    type: "MULTIPLE_CHOICE",
    difficulty: "MEDIUM",
    topicId: "software-engineering",
    topicName: "Software Engineering",
    reviewMode: getQuestionReviewMode("MULTIPLE_CHOICE"),
    usageCount: 2,
    updatedAt: "2026-04-08T16:55:00.000Z",
    answerPreview: ["Client-server", "Statelessness", "Cacheability", "Uniform interface"],
    explanation:
      "REST emphasizes a set of architectural constraints rather than a specific protocol or serialization format.",
  },
  {
    id: "Q-281",
    stem: "Explain the CAP theorem and state which tradeoff a distributed data store makes during a network partition.",
    type: "SHORT_TEXT",
    difficulty: "HARD",
    topicId: "distributed-systems",
    topicName: "Distributed Systems",
    reviewMode: getQuestionReviewMode("SHORT_TEXT"),
    usageCount: 1,
    updatedAt: "2026-04-11T13:35:00.000Z",
    answerPreview: [
      "During a partition, the system must choose between consistency and availability while partition tolerance remains mandatory.",
    ],
    explanation:
      "The response should note that partition tolerance is unavoidable once partitions occur, forcing a consistency-availability tradeoff.",
  },
  {
    id: "Q-288",
    stem: "When does Dijkstra's algorithm fail to produce correct shortest paths in a weighted graph?",
    type: "SINGLE_CHOICE",
    difficulty: "MEDIUM",
    topicId: "algorithms",
    topicName: "Algorithms",
    reviewMode: getQuestionReviewMode("SINGLE_CHOICE"),
    usageCount: 3,
    updatedAt: "2026-04-05T11:05:00.000Z",
    answerPreview: ["When negative edge weights are present"],
    explanation:
      "Dijkstra assumes once a node is finalized its current path cost is optimal, which breaks with negative-weight edges.",
  },
];
